### PR TITLE
Use constants and DRY

### PR DESCRIPTION
**Pull request by AlexeySoshin**

### CODE REVIEW

**Comment by FZambia** [comment]
Hello! Thanks for work on this but I don't feel this is correct way to use constants. In my opinion with this patch we have less readable file – when we want to see available options we should first look at places where we bind viper variables and then find a value in a list of constants. So general impression here is that we changed string constants to constants defined as variables.

I like the idea to be more DRY in places where we bind variables though. But without using variable constants. I mean sth like this:
```go
bindEnvs := []string{"debug", "engine", "insecure", ...}

for _, env := range bindEnvs {
    viper.BindEnv(env)
}
```
Instead of this:
```go
bindEnvs := []string{DEBUG, ENGINE, INSECURE...}

for _, env := range bindEnvs {
    viper.BindEnv(env)
}
```

**Comment by AlexeySoshin** [comment]
In my opinion, constants will also make your code refactoring easier, instead of find&replace.
And you don't produce GC this way.
But it's your choice, of course.

**Comment by FZambia** [comment]
I still convinced that we lose in readability introducing constants here. It was never a problem modifying options in this file and all these options are not going to change often as we mostly only add new. I'll fix repetitions in `.BindEnv` and `.BindPFlag` though.

**Comment by FZambia** [comment]
Changed in eb363e4b2332677c8ae7583c1acbe2ca16579526. Sorry for not accepting your changes – maybe I realize my wrong vision later and refactor like you suggested.

**Comment by AlexeySoshin** [comment]
No problem, those are only suggestions.
And if you'll use arrays for configurations, that will be fine by me.

**Pull request closed without merging**
