### PR TITLE
Have a "Channel only" and "Channel incl. prefix" types.

### PR DESCRIPTION
**Pull request by klauspost**
As you proposed.

### CODE REVIEW

**Comment by klauspost** [comment]
I must say, I am extremely impressed that this hasn't shown any existing errors. I had expected at least one, maybe up to three minor mistakes to show up from this change.

But I guess that is the advantage of using existing, tested code as a base.

**Comment by klauspost** [comment]
Shortly I will be away (as in email only) until Sunday. 

I don't have any more changes right now, but when I get back I might want to look at writing benchmarks, so we maybe could see how things perform. This will also likely be able to act as a race detector.

**Comment by FZambia** [comment]
Just transferred admin changes myself)))

**Comment by klauspost** [comment]
Cool :)

**Comment by FZambia** [comment]
Have a nice weekend!

**Pull request closed without merging**
