### PR TITLE
Proxy authentication, RPC, refresh calls to application backend

### PR DESCRIPTION
**Pull request by FZambia**
This pr allows to proxy several calls to app backend. With some additions in config like this:

```json
{
         ...
	"proxy_connect_endpoint": "http://localhost:3000/centrifugo/connect",
	"proxy_connect_timeout":  1,
	"proxy_rpc_endpoint":     "http://localhost:3000/centrifugo/rpc",
	"proxy_rpc_timeout":      1,
	"proxy_refresh_endpoint": "http://localhost:3000/centrifugo/refresh",
	"proxy_refresh_timeout":  1,
}
```

* Connection requests **without token set** will be proxied to `proxy_connect_endpoint`. This means you don't need to generate JWT token and pass it to client and can for example rely on cookie while authenticating user (of course Centrifugo should work on same domain in this case so your site cookie passed to Centrifugo on connect). This also means that **every** new connection from user will result in HTTP request to your backend. While with JWT token you usually generate it once on application page reload, if client reconnects due to Centrifugo restart or internet connection loss it uses the same JWT it had before thus usually no additional requests generated during reconnect process (until token expired).
* RPC calls over client connection will be proxied to `proxy_rpc_endpoint`. This will allow developer to utilize websocket connection in bidirectional way.
* Expiring connection refresh will call `proxy_refresh_endpoint` to refresh connection. When set server-side refresh will be used (i.e. Centrifugo will ask your backend about connection validity) instead of refresh workflow on client side.

All calls are HTTP POST requests which proxy `Cookie`, `User-Agent`, `X-Real-Ip`, `X-Forwarded-For`, `X-Request-Id`, `Authorization` headers and include some additional info as JSON body (for example data sent by client in RPC call etc).

Looking for feedback on this at moment. It will be great to hear about possible use cases before merging this to upstream. 

Partly relates to #195

### CODE REVIEW

**Comment by FZambia** [comment]
Payload sent to app backend in connect request:

```json
{"client":"9336a229-2400-4ebc-8c50-0a643d22e8a0","transport":"websocket","encoding":"json"}
```

Response expected:

```json
{"credentials": {"user": "56", "exp": 0}}
```

Payload sent to app backend in refresh request:

```json
{"client":"bbc9b067-1ddd-4e1b-a8fb-0183dfa101bb","user":"56"}
```

Response expected:

```json
{"credentials": {"exp": 1565436268}}
```

where `exp` in timestamp when connection must be considered expired

Payload sent to app backend in RPC request:

```json
{"encoding":"json","client":"0558cf54-bc0f-4970-9c74-3badd636bede","user":"56","data":{"method":"getCurrentYear"}}
```

Response expected:

```json
{"data": {"method": "getCurrentYear"}}
```

Application backend can return JSON object that contain an error to return to client:

```json
{
  'error': {
    'code': 1000,
    'message': 'custom error'
  }
}
``` 

Or disconnect object to disconnect client:

```json
{
  'disconnect': {
    'code': 4000,
    'reconnect': False,
    'reason': 'custom disconnect'
  }
}
```

**Comment by FZambia** [comment]
Added a related pull request that solves a problem that mobile clients that mostly send JSON payloads over Protobuf protocol will have proxied payloads in base64. With pull request https://github.com/centrifugal/centrifuge/pull/65 server will assume that payload is JSON by default until explicitly set as binary by client.

**Comment by joshdvir** [comment]
I like the way this PR is going but I do have a few questions and I will address every request

1. Connect -  I like this very much as you wrote we can use cookies to authenticate instead of JWT.
2. Refresh - not sure why this is needed, also if Centrifugo will call the backend how will Centrifugo will forward any cookies, etc.. ? since I want to refresh based on the cookie the client has.
3. RPC - I like the option of sending messages from the client to the backend via Centrifugo, the way I implemented it in few of my apps was having the backend also connect to Centrifugo via Websockets and clients would send messages only to specific channels, I like the way it is here but  I would want options like only for specific channels forward to the backend and more.
This option can be very heavy on the backend if many clients will send messages.

This is a good PR, thanks :)

**Comment by FZambia** [comment]
Thanks for feedback @joshdvir !

> Connect - I like this very much as you wrote we can use cookies to authenticate instead of JWT.

Cool! Just had an idea today - not for MVP introduced here but for future maybe. Application backend can return `token` field in response on connect request. This token will be sent to client by Centrifugo. Since this moment client can reconnect to Centrifugo using JWT token with all mechanics about expiration etc. But this requires more consideration and some protocol enhancements. Just for a record for now...

> Refresh - not sure why this is needed, also if Centrifugo will call the backend how will Centrifugo will forward any cookies, etc.. ? since I want to refresh based on the cookie the client has.

First of all this will simplify client side as refresh workflow requires a piece of pretty difficult code to maintain in our client libraries. I think having this as alternative way to client-side refresh is good for adoption.

When Centrifugo makes request it sends user ID in request JSON to application backend as it is already known. And finally Centrifugo sends cookie received on connect from client. So if you don't have cookies that can be dynamically changed while client connected then I suppose you can properly validate this session. I suppose at this moment you make decisions based on user ID in most situations. Even if cookie is not actual I suppose your session backend should detect this and reject validation. Or am I missing sth in this process?

>  I like the way it is here but I would want options like only for specific channels forward to the backend and more.

RPC is not related to channels at moment - this is a top-level method of client. So I think we can't bind this logic to channels somehow. Client can call RPC over WebSocket/SockJS even without being subscribe to any channel.

> This option can be very heavy on the backend if many clients will send messages.

Yeah, there could be lots of RPC requests but this is almost the same if client just did lots of calls via AJAX at moment I suppose. Or you mean sth specific saying this?

**Comment by joshdvir** [comment]
Again I'm not sure about the refresh if it disconnects I want the client to reconnect.
I don't think that the cookie that was sent in the initial connect would help validate the user if it has some expire value.
The RPC calls are cool but the reason we still use AJAX is the guaranty that the request is finished successfully and I'm not sure you can guaranty that or even want to do that, which makes me think what type of messages would you use that for?
for me, the most valuable is the connect option which allows me to use the current auth method for the app also for Centrifugo.

**Pull request merged**
