### PR TITLE
support go.mod for build

### PR DESCRIPTION
**Pull request by hetao29**
## Proposed changes

support go.mod for build

### CODE REVIEW

**Comment by FZambia** [comment]
@hetao29 hello!

I don't have plans to migrate to Go modules from Dep without good reason at this moment as Dep seems to work just fine. I already support two ways of managing dependencies in Centrifuge library (dep and go mod). In case of library this makes sense. In case of building server I prefer to have one way. Could you describe why you need go mod and why dep does not work for you?

I also have some questions to changes in this pr but I suppose I can ask them later after the need in this addition will be obvious.

**Comment by hetao29** [comment]
@FZambia thanks for reply.

go.mod is not necessary, just I build it use go.mod.

**Comment by FZambia** [comment]
@hetao29 I think eventually we will move this repo to go mod as dep is not actively maintained anymore and requires GOPATH. But I have to make sure that nothing broken in release build process. Your pull request has some overcomplications. You don't need to replace internal package paths, go mod can automatically migrate from dep to go mod - just run `go mod init`. This way it should generate `go.mod` file like this:
```
module github.com/centrifugal/centrifugo

go 1.13

require (
	github.com/FZambia/eagle v0.0.1
	github.com/FZambia/statik v0.1.2-0.20180217151304-b9f012bb2a1b
	github.com/FZambia/viper-lite v0.0.0-20171108064948-d5a31e6aa18b
	github.com/ajstarks/svgo v0.0.0-20180226025133-644b8db467af
	github.com/centrifugal/centrifuge v0.2.3-0.20191120071108-53f68cdc8627
	github.com/gogo/protobuf v1.3.1
	github.com/gorilla/securecookie v1.1.1
	github.com/inconshreveable/mousetrap v1.0.0 // indirect
	github.com/mattn/go-isatty v0.0.3
	github.com/mitchellh/mapstructure v0.0.0-20180511142126-bb74f1db0675 // indirect
	github.com/pelletier/go-toml v1.1.0 // indirect
	github.com/prometheus/client_golang v0.9.2
	github.com/rs/zerolog v1.9.2-0.20180928011143-8e36cbf881d3
	github.com/satori/go.uuid v1.2.0
	github.com/spf13/cast v1.2.0 // indirect
	github.com/spf13/cobra v0.0.3
	github.com/spf13/jwalterweatherman v0.0.0-20180109140146-7c0cea34c8ec // indirect
	github.com/spf13/pflag v1.0.1 // indirect
	github.com/stretchr/testify v1.3.0
	golang.org/x/crypto v0.0.0-20191119213627-4f8c1d86b1ba
	golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3
	google.golang.org/genproto v0.0.0-20180514194645-7bb2a897381c // indirect
	google.golang.org/grpc v1.14.0
	gopkg.in/yaml.v2 v2.2.1 // indirect
)
```

This way internal packages will work just fine.

Then `go mod vendor` vendors all dependencies so we can replace current `vendor` folder with one generated by `go mod`.

Then simply run:

```
go run main.go
```

Or if you want to run using vendored dependencies:

```
go run -mod vendor main.go
```

**Comment by hetao29** [comment]
I try your go.mod and my go.mod ,both error is:
`go: downloading github.com/ajstarks/svgo v0.0.0-20180226025133-644b8db467af
go: finding github.com/centrifugal/centrifugo/internal latest
go: finding github.com/centrifugal/centrifugo/internal/middleware latest
go: finding github.com/centrifugal/centrifugo/internal/health latest
go: finding github.com/centrifugal/centrifugo/internal/admin latest
go: finding github.com/centrifugal/centrifugo/internal/api latest
go: finding github.com/centrifugal/centrifugo/internal/metrics latest
go: finding github.com/centrifugal/centrifugo/internal/metrics/graphite latest
go: finding github.com/centrifugal/centrifugo/internal/webui latest
go: extracting github.com/ajstarks/svgo v0.0.0-20180226025133-644b8db467af
go: finding github.com/ajstarks/svgo v0.0.0-20180226025133-644b8db467af
build github.com/centrifugal/centrifugo: cannot load github.com/centrifugal/centrifugo/internal/admin: no matching versions for query "latest"
go build -v -o bin/centrifugo main.go
go: finding github.com/centrifugal/centrifugo/internal latest
go: finding github.com/centrifugal/centrifugo/internal/admin latest
go: finding github.com/centrifugal/centrifugo/internal/middleware latest
go: finding github.com/centrifugal/centrifugo/internal/health latest
go: finding github.com/centrifugal/centrifugo/internal/webui latest
go: finding github.com/centrifugal/centrifugo/internal/api latest
go: finding github.com/centrifugal/centrifugo/internal/metrics/graphite latest
go: finding github.com/centrifugal/centrifugo/internal/metrics latest
build command-line-arguments: cannot load github.com/centrifugal/centrifugo/internal/admin: no matching versions for query "latest"
make: *** [build] Error 1`

my go.mod 
`
module github.com/centrifugal/centrifugo

go 1.13

require (
	github.com/FZambia/statik v0.1.2-0.20180217151304-b9f012bb2a1b
	github.com/FZambia/viper-lite v0.0.0-20171108064948-d5a31e6aa18b
	github.com/ajstarks/svgo v0.0.0-20191124160048-bd5c74aaa11c
	github.com/centrifugal/centrifuge v0.2.3
	github.com/gorilla/securecookie v1.1.1 // indirect
	github.com/mattn/go-isatty v0.0.3
	github.com/mitchellh/mapstructure v1.1.2 // indirect
	github.com/pelletier/go-toml v1.6.0 // indirect
	github.com/prometheus/client_golang v0.9.2
	github.com/rs/zerolog v1.17.2
	github.com/satori/go.uuid v1.2.0
	github.com/spf13/cast v1.3.0 // indirect
	github.com/spf13/cobra v0.0.3
	github.com/spf13/jwalterweatherman v1.1.0 // indirect
	github.com/spf13/pflag v1.0.5 // indirect
	golang.org/x/crypto v0.0.0-20191128160524-b544559bb6d1
	google.golang.org/genproto v0.0.0-20191115221424-83cc0476cb11 // indirect
	google.golang.org/grpc v1.19.0
	gopkg.in/yaml.v2 v2.2.7 // indirect
)
`

**Pull request closed without merging**
