### PR TITLE
Clean up responses

### PR DESCRIPTION
**Pull request by klauspost**
* Remove custom marshalling of responses.
* Set error via function call.
* Remove toJson since it no longer serves any purpose.

### CODE REVIEW

**Comment by FZambia** [comment]
This looks fantastic! Thanks so much for your help, I'll check and merge this in the evening after my work.

**Comment by klauspost** [comment]
Hold a little longer, I think it can be made even better.

**Comment by klauspost** [comment]
Small change response.Err() now returns a bool, so it can be used for checks as well.

So it can be used like this:
```Go
    if resp.Err(someFunction()) {
        return resp
    }
```
Instead of:
```Go
    err = someFunction()
    if err != nil {
        resp.Err(err)
        return resp
    }
```
In cases where the function returns an error we want to pass on.

**Comment by FZambia** [comment]
Merged!

**Pull request merged**
