### PR TITLE
Rename a whole bunch of funtions to a shorter version.

### PR DESCRIPTION
**Pull request by klauspost**
I have gone through the project, and changed many of the names to a more go idiomatic form.

See for instance [What's in a name?](http://talks.golang.org/2014/names.slide#1). I guess a lot comes from the python heritage.

Most of what I have changed:
* Avoid 'get', 'set', 'handle' prefixes where it makes sense.
* Shorten a few types `Connection` -> `Conn`, `Command` -> `Cmd`, 
* Change some member variables to shorter versions.

I haven't done anything to local variables or exported functions.

I can see it no longer merges, but i can of course re-base if you don't object to the idea.

### CODE REVIEW

**Comment by FZambia** [comment]
Oh.. such a hard work! And yes, all my method names came from Python))

If you rebase – it will be fine! I like and agree with most of changes except several ones:

* `Lifetime` - I prefer `ConnectionLifetime` (as this will be read as project lifetime which is semantically wrong because this is connection lifetime and I also like that it corresponds to name in `json`)
* `projByKey` - I think `projectByKey` better
* `ses` - think `sess` better
*  I'd try to change `c.Info` in some way as `info()` returns `ClientInfo` full of different fields while `c.Info` is just default `[]byte` client info
* `privateCh` - I prefer `privateChannel` as I think `Ch` is frequently used for Go channels
* and the last one - IMO `namespaceName()` is better than `channelNs` because `Ns` is not so common abbreviation

I can do all changes myself after merge - absolutely no problem

Thanks a lot for all you do for Centrifugo - your help is priceless!

**Comment by klauspost** [comment]
Nah - only about an hour and a half of work with [gorename](https://texlution.com/post/gorename/). 

Your comments all make sense. I will adjust the PR.

**Comment by klauspost** [comment]
Changed most.

>I'd try to change `c.Info` in some way as `info()` returns ClientInfo full of different fields while `c.Info` is just default `[]byte` client info.

I actually investigated this quite a bit. Would it be more precise if it was infoCache, or what does it actually contain?

* Made it `ConnLifetime` to be in line with the common abbreviations.
* Made it `channelNamespace`, since `namespaceName` is a bit weird :)

**Comment by FZambia** [comment]
I think this must be called just a `defaultInfo`

**Comment by klauspost** [comment]
Changed

**Comment by FZambia** [comment]
Merged!

**Comment by FZambia** [comment]
Thank you very much!

**Pull request merged**
