### PR TITLE
Reducing the size of docker image

### PR DESCRIPTION
**Pull request by yurtaev**
265.6 MB => 24.69 MB

### CODE REVIEW

**Comment by yurtaev** [comment]
The minimal working example: https://dl.dropboxusercontent.com/u/714800/cent_mini.zip

```bash
$ docker-compose build
$ docker-compose up
```

**Comment by FZambia** [comment]
Wow, the difference is really essential! 

Several moments here. First, what about tweaking nofile limit? Also, I am not a docker user yet, how to run centrifugo from centrifugo user? I am also not sure is it ok to just change base image (as existing users already use image based on centos 7)? Are there any known open-source network servers that use this base image?

**Comment by yurtaev** [comment]
1. The latest docker supports setting ulimits through the command line and the API 
	- https://blog.docker.com/2015/04/docker-release-1-6/
	- https://github.com/docker/docker/pull/9437

	```
	docker run --ulimit=nofile=40000:40000 -v /your/host/dir/containing/config/file:/centrifugo -p 8000:8000 fzambia/centrifugo centrifugo -c config.json
	```
2. For example https://hub.docker.com/_/docker/ https://github.com/docker-library/docker/blob/e33e7226872e53dfa88bee09f153704a66fc103d/1.9/Dockerfile

**Comment by FZambia** [comment]
Ah, it seems that I missed some instructions as they were suppressed in Github diff - I missed `USER` directive already used in Dockerfile:( So no questions about running as user anymore.

Btw it's time to add SHA256 sum into Dockerfile.

So the last thing that confuses me – backwards compatibility concerns. Can we can just change base image in Dockerfile? Also ulimit must be configured from outside (which I think is nice but breaks current usage scenarios).

**Comment by FZambia** [comment]
@yurtaev added your Dockerfile into documentation in Docker chapter - https://fzambia.gitbooks.io/centrifugal/content/deploy/docker.html

Btw do you know will Docker override limits set in `/etc/security/limits.d` when we provide limits via command-line arguments when starting container?

**Comment by FZambia** [comment]
@yurtaev Egor, just create image based on your pull request in another repo (https://github.com/centrifugal/centrifugo-docker) - also on Docker hub https://hub.docker.com/r/centrifugo/centrifugo/ - I think this will resolve all my doubts about compatibility

**Comment by FZambia** [comment]
Thanks a lot for your contribution!

**Pull request closed without merging**
