### PR TITLE
lite queue refactor

### PR DESCRIPTION
**Pull request by LopatkinEvgeniy**

### CODE REVIEW

**Comment by FZambia** [comment]
@LopatkinEvgeniy hello, thanks:)  I agree with second change, but prefer to avoid using defer when adding a message into queue. Can we leave only loop change here?

**Comment by LopatkinEvgeniy** [comment]
Yes of course

**Comment by LopatkinEvgeniy** [comment]
Why you increase size in method resize? I think would be better to increasr capacity. In this way there will be no need in fields tail and ctn... 
```
q.tail == len(q.nodes) 
q.ctn == len(q.nodes[q.head:])
```

**Comment by FZambia** [comment]
I am not an original author of this code - you can see a reference to [this post](https://blog.dubbelboer.com/2015/04/25/go-faster-queue.html) in source code. This is an adapted version of queue described there. Regarding to your question:

> Why you increase size in method resize? I think would be better to increase capacity.

Because `To increase the capacity of a slice one must create a new, larger slice and copy the contents of the original slice into it.` - see [this](https://blog.golang.org/go-slices-usage-and-internals) post. 

Also resize works both ways - to increase and decrease size - if we were using slicing when decreasing we still have a reference to an underlying array which can't be garbage collected.

I don't want to refactor queue implementation until it will be a bottleneck or have any known problems as it's rather important and stable part of Centrifugo.

**Comment by LopatkinEvgeniy** [comment]
Ok, i'll roll back the changes

**Pull request merged**
