### PR TITLE
Add strong types for ID types.

### PR DESCRIPTION
**Pull request by klauspost**
Example for Issue #12 for discussion. Just did a conversion of 4 major types. As I hope you'll agree it is very unintrusive, and later on we can change the variable names to something shorter, since the type implies what it is.

The actual name of each type is easy to change. I wasn't sure if uuid is one type, so I kept that as a string for now.

I am heading to bed now, but I can continue to work on it tomorrow.

### CODE REVIEW

**Comment by FZambia** [comment]
Ok let's rename all to 

```go
type (
    ProjectKey string
    NamespaceKey string
    Channel string
    UserID string
)
```

Maybe these names a bit longer but they will allow to make function arguments shorter so instead 

```go
func (s *structure) channelOpts(projectKey, namespaceName string) *ChannelOptions {
}
```
we can write
```go
func (s *structure) channelOpts(pk ProjectKey, nk NamespaceKey) *ChannelOptions {
}
```

**Comment by FZambia** [comment]
Could you also change `ChannelID` to just `Channel`? I don't like ID suffix when it's not an ID actually - channel can be the same in different projects.

**Comment by klauspost** [comment]
>Could you also change ChannelID to just Channel? I don't like ID suffix when it's not an ID actually - channel can be the same in different projects.

Done. Also found a rather easy way to change function parameter names, so I changed a lot of `channel Channel` to `ch Channel`.

**Comment by FZambia** [comment]
Yep, thanks a lot!

**Comment by klauspost** [comment]
The reason I personally prefer ChannelID is because the content of the type is not the channel "itself", but rather an ID to find it. But the way it is structured not, it makes ok sense.

**Comment by FZambia** [comment]
mm.. just looked at code more carefully. Let's see at this method:
```
func (app *application) projectChannel(pk ProjectKey, ch Channel) Channel {
    return Channel(app.config.channelPrefix + "." + string(pk) + "." + string(ch))
}
```
Until this moment Channel is what we mean as channel in Centrifugo - but the result of this method can't be Channel too. So the result must be `ChannelID`

```
func (app *application) projectChannel(pk ProjectKey, ch Channel) ChannelID {
    return ChannelID(app.config.channelPrefix + "." + string(pk) + "." + string(ch))
}
```

I think in this case we will get a nice separation between what is `Channel` and what is `ChannelID`

**Comment by FZambia** [comment]
and this must be something like:
```go
func (app *application) channelID(pk ProjectKey, ch Channel) ChannelID {
    return ChannelID(app.config.channelPrefix + "." + string(pk) + "." + string(ch))
}
```
as I learned from all your changes)))

**Comment by FZambia** [comment]
I'll make it!

**Comment by klauspost** [comment]
Too late #15  :D

**Comment by FZambia** [comment]
ooops:) just pushed my own changes:)

**Comment by FZambia** [comment]
Now it's in proper state)))

**Pull request merged**
