### PR TITLE
Add uid parameter to publish command to allow client to define uid

### PR DESCRIPTION
**Pull request by vladshut**
This functionality allows to push notification with specified uid to centrifugo. Also server can send notifications directly (without centrifugo) to client with specified uid and client can fetch notifications from centrifugo started from specified uid by server.

### CODE REVIEW

**Comment by FZambia** [comment]
@vladshut thanks, this is much better than previous approach.

But I am still waiting for real use case information behind this change. Could you describe it in details?

**Comment by vladshut** [comment]
@FZambia 
This functionality allows to push notification with specified uid to centrifugo. Also server can send notifications directly (without centrifugo) to client with specified uid and client can fetch notifications from centrifugo started from specified uid by server.

**Comment by damour** [comment]
Hi @FZambia ! Thanks for prompt response. Some background. At our site in header user can see his  message counter (in internal mail). Frontend is classic web application (not single-page application) so after some actions page reloads. After page loading/reloading user see his message counter. Then we subscribe to user notification channel and update message counter.
Backend - microservices that communicates via async messages.

Problem: user can missing some messages.

Registration use case:
- user click "register" button, controller in user service push welcome message to user notification channel, sends async UserRegistered message to message bus and return response to user.
- page loaded, user see 1 message.
... at this moment background workers sends another messages to user
- we subscribe to user channel.

Result: user see 1 message.
Expected result: user see 2 messages in message box.

Proposed solution: when page rendering we store last message uid with counter. Then in subscribe command we provide last id:  {channel: "notifications", last: lastMessageUId, recover: true}. So centrifugo restore messages and user see actual info.

**Comment by FZambia** [comment]
@damour thanks for detailed explanation, do you need assistance from `centrifuge-js` side for this to work? Looks like you need [this pr](https://github.com/centrifugal/centrifuge-js/pull/44) to be merged?

**Comment by damour** [comment]
We use centrifugo beyond api gateway:
client (graphql subscription) -> api gateway(nodejs websocket client) -> centrifugo.
Therefore, for us it is not mandatory, but for other users it will definitely be useful. Thanks!

**Pull request merged**
