### PR TITLE
Fix: code quality issues

### PR DESCRIPTION
**Pull request by withshubh**
##### Description
Hi :wave: 
I ran the [DeepSource](https://deepsource.io) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/withshubh/centrifugo/issues/?category=recommended). I have fixed a few of them in this PR.

#### Summary of changes
- Removed unused code
- Removed redundant return statement
- added .deepsource.toml

### CODE REVIEW

**Comment by FZambia** [comment]
@withshubh hello, thanks! But seems that I just fixed this in #417

**Comment by withshubh** [comment]
There are [more issues](https://deepsource.io/gh/withshubh/centrifugo/issues/?category=recommended) in this repo which you might want to have a look.

**Comment by FZambia** [comment]
@withshubh thanks, addressing file perm warning in #418 , other issues look minor enough. Thanks for pr - I'll take a closer look at DeepSource in the future.

**Comment by withshubh** [comment]
Thanks @FZambia 😊

**Comment by FZambia** [comment]
At this moment I prefer to not integrate so such an issue will be pretty stale and probably closed. Integration is simple enough – if I decide this is a right move we'll do this.

BTW, does DeepStream.io supports one-time repo analysis without full integration?

**Comment by withshubh** [comment]
> At this moment I prefer to not integrate so such an issue will be pretty stale and probably closed. Integration is simple enough – if I decide this is a right move we'll do this.
> 
> BTW, does DeepSource.io support one-time repo analysis without full integration?

As of now there is no option to run one time analysis but we're working on CLI that will help you do so.

**Comment by withshubh** [comment]
Hey @FZambia :wave: I hope you're doing good.

Just wanted to share that DeepSource released [CLI](https://deepsource.io/docs/config/cli.html) last month. I would really appreciate it if you could try it out and share your feedback with us. : )

**Comment by FZambia** [comment]
@withshubh hello, great to hear! I don't want to create account on deepsource to test this feature out.

**Pull request closed without merging**
