### PR TITLE
Add handling of server shutdowns.

### PR DESCRIPTION
**Pull request by klauspost**
* Reject all incoming requests once shutdown has been initiated
* Finish all incoming requests pre-shutdown.
* Unsubscribe users from their channels. (stage 1)
* Flush all outgoing messages and unsubscribe users (stage 2).
* Send "shutting down" to all admins.

### CODE REVIEW

**Comment by klauspost** [comment]
I only have two issues:
* [ ] Add 'shutdown' package to godep. I haven't used it. Maybe you could help me?
* [ ] Tests, but I want to make sure that this is the right way to go.

I don't know if there are other things that should be done on shutdown? Should we do something with Redis?

**Comment by FZambia** [comment]
As far as I know Godep just remember commits of versions - you don't need to add shutdown to any register.

In Redis.There is a queue of API messages, presence and history. Presence will be removed automatically as we unsubscribe from all channels. History is OK to stay in Redis. And we don't need to clean queue as we shutdown one instance of Centrifugo and this queue will be used by other instances. So nothing to do with Redis I think.

**Comment by FZambia** [comment]
Personally I think that unsubscribing on shutdown is enough - all other things just make code more complicated and do not give any prize in practice in my opinion. How users of Centrifugo should behave when shutdown occurres?

**Comment by FZambia** [comment]
I also think that the far actual shutdown will occur the faster load balancer will start routing new requests to other instances

**Comment by FZambia** [comment]
Thought about this a little more while went from work to home:) In practice at our work we remove node from upstream in Nginx - so API requests and connections go to another node. And then stop a node. Sending remaining messages suppose high message rate - in this case client will lose new messages anyway while reconnecting. Moreover it will miss some messages as we don't send new messages to him. Unsubscribing from channels is a nice new feature because we get actual presence info in Redis. Otherwice old connections will be in presence info until expire (~25 sec).

**Comment by klauspost** [comment]
>We also need to not accept new API requests in apiHandler - but what will application do in this case.

It will return at once with a http.StatusServiceUnavailable (503) shutdown is initiated. This should be enough for nginx to choose another node for instance.

> And then stop a node. Sending remaining messages suppose high message rate - in this case client will lose new messages anyway while reconnecting

Yes, and in case of a redis engine, any incoming messages will still be processed and sent to other clients, as well as be in history.

>Unsubscribing from channels is a nice new feature because we get actual presence info in Redis.

Yes.

**Comment by FZambia** [comment]
I still can not understand why sending remaining messages to clients is important.

Without sending remaining messages when node stops:
* client unsubscribed from all channels
* node stopped, client disconnected
* client loses new messages while reconnecting to another node
* client reconnects and everything is fine again

With sending remaining:
* client unsubscribed from all channels
* then we send remaining messages (btw clients already technically already unsubscribed from all channels and should not receive those messages)
* node stopped, client disconnected
* client loses new messages while reconnecting to another node
* client reconnects and everything is fine again

In both cases client can lose messages so in my opinion flushing remaining messages is overcomplicated and unnecessary step. And it's absolutely OK to just unsubscribe clients from channels and stop a node. Maybe I miss something?

**Comment by klauspost** [comment]
>clients already technically already unsubscribed from all channels and should not receive those messages.
Messages already queued up in 'client' doesn't care if you are still subscribed. If they have been routed to the client they will be sent.

But in stage 1, we unsubscribe, so no *additional* messages can be sent. In stage 2 we flush any that may have been queued up.

So

**pre shutdown**: Finish processing any commands that hasn't finished processing.
**stage 1**: Unsubscribe users.
**stage 2**: flush any messages still left in the `client.messages` queue.

We could consider sending a "shutting down, please reconnect" message to users. But that is easy to put in later.

I think in all cases it is preferable to send what is queued up if possible.

Regarding Redis, I think we should add a shutdown check here: https://github.com/centrifugal/centrifugo/blob/master/libcentrifugo/engineredis.go#L200 - when shutdown has started we shouldn't process more incoming messages. Agree?

**Comment by FZambia** [comment]
Still don't agree. Imagine a situation. One of Centrifugo nodes is under heavy load, too many messages queued up and there are clients to which sending remaining messages takes a lot of time. We added another couple of nodes to upstream and want clients to reconnect to it. As connections persistent we want to restart a node which is under load so clients reconnect to old one and newly added nodes from scratch. In this case we will be waiting a long time to stop a node and then start it. Meanwhile we lose or drop a lot of new messages. Why new messages is less important than old queued messages?

**Comment by klauspost** [comment]
>[...]One of Centrifugo nodes is under heavy load [...]

Ah - I think I found out why we see things differently. When discussing shutdowns, I don't see server re-balancing as a something that should be solved that way.  

In my eyes that should be handled by a separate function you can message with a command, like "disconnect 50% of all connections" or something similar. That would be much more gentle, and will not load the other servers. In my experience shutting down a server on overload is much more likely to create a cascade effect, that can bring down your entire cluster.

**Comment by FZambia** [comment]
I have a sense that you are right in everything you say. But I also think that Centrifugo does not need this at moment as code become too complicated while I still don't see lot of practical benefit from these changes. Maybe several installations in production in future reveal the need and real benefit of sending remaining messages. Can we just leave unsubscribing from all channels for now and see how it goes?

**Comment by FZambia** [comment]
:(

The option does not remove code complexity added here. I think that in early development stages simple code base is very important (for me). I am not comfortable with shutdown code changes - too many logic which does not help with losing messages as client will lose them anyway while reconnecting. Please, let's go with unsubscribing clients from channels only at moment and will add sending remaining messages to clients only if really needed in future releases?

**Comment by klauspost** [comment]
Whatever you want. I will keep the code, and you can add it later. I don't want to waste more time on it, and now it seems like there is a tons of conflicts to be resolved, which I don't have the time for.

**Comment by FZambia** [comment]
Ok, sorry for conflicts, will try to add unsubscribing myself today in the evening:)

**Pull request closed without merging**
